### ISSUE TITLE
Tunnels appear to erase themselves shortly after creation

### ISSUE THREAD

**Issue by kav** [webrelay/ingress#1]
`relay tunnel create --group webrelay-ingress mytunnel` responds with
\<ID\>.webrelay.io<---->http://127.0.0.1
but then running `relay ing ls` shows nothing.

Watching the webUI and refreshing at the right time a relay does briefly appear, and then disappear...

Not sure this is an ingress issue but I'm trying to wire it to an ingress controller and can't since it keeps erasing itself.

**Comment by rusenask** [comment]
Hi @kav, there were some recent changes to the ingress controller on how it figures out it's same so there can be multiple controllers running in different clusters without deleting each others tunnels. I guess there was a regression for free tier use case. If you can send me your username (info@webhookrelay.com), I can enable custom subdomains for you so it will work for you.
